In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = {
    "Catogery" : ['A','B','A','B','A','B','A'],
    "Store" : ['S1','S2','S3','S1','S2','S2','S1'],
    "Sales" : [90,66,44,80,39,77,56],
    "Quantity" : [55,77,88,46,90,89,34],
    "Date" : pd.date_range("2026-4-23",periods=7)
    
}

df = pd.DataFrame(data)
df

  Catogery Store  Sales  Quantity       Date
0        A    S1     90        55 2026-04-23
1        B    S2     66        77 2026-04-24
2        A    S3     44        88 2026-04-25
3        B    S1     80        46 2026-04-26
4        A    S2     39        90 2026-04-27
5        B    S2     77        89 2026-04-28
6        A    S1     56        34 2026-04-29

In [3]:
df

  Catogery Store  Sales  Quantity       Date
0        A    S1     90        55 2026-04-23
1        B    S2     66        77 2026-04-24
2        A    S3     44        88 2026-04-25
3        B    S1     80        46 2026-04-26
4        A    S2     39        90 2026-04-27
5        B    S2     77        89 2026-04-28
6        A    S1     56        34 2026-04-29

In [4]:
total_of_b = df.groupby("Catogery") ["Sales"].sum()
total_of_b

Catogery
A    229
B    223
Name: Sales, dtype: int64

In [5]:
total_of_a = df.groupby(["Catogery","Store"]) ["Sales"].sum()
total_of_a

Catogery  Store
A         S1       146
          S2        39
          S3        44
B         S1        80
          S2       143
Name: Sales, dtype: int64

In [6]:
df["Sales"].mean()

np.float64(64.57142857142857)

In [7]:
df

  Catogery Store  Sales  Quantity       Date
0        A    S1     90        55 2026-04-23
1        B    S2     66        77 2026-04-24
2        A    S3     44        88 2026-04-25
3        B    S1     80        46 2026-04-26
4        A    S2     39        90 2026-04-27
5        B    S2     77        89 2026-04-28
6        A    S1     56        34 2026-04-29

In [8]:
df["Sales"].agg(["sum","max","min","mean","count","std","median"])

sum       452.000000
max        90.000000
min        39.000000
mean       64.571429
count       7.000000
std        19.112449
median     66.000000
Name: Sales, dtype: float64

#new pivottable

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
data = {
    "date" : pd.date_range("2026-4-24",periods=20),
    "product" : ['A','B','C','D'] * 5,
    "region" : ["east","west","south","north"] *5,
    "sales" : np.random.randint(100,1000,20),
    "unites" : np.random.randint(10,100,20),
    "rep" : ["jhon","bob","david","max"] *5
}

df = pd.DataFrame(data)
df

         date product region  sales  unites    rep
0  2026-04-24       A   east    383      41   jhon
1  2026-04-25       B   west    991      88    bob
2  2026-04-26       C  south    468      44  david
3  2026-04-27       D  north    326      45    max
4  2026-04-28       A   east    467      26   jhon
5  2026-04-29       B   west    966      23    bob
6  2026-04-30       C  south    855      45  david
7  2026-05-01       D  north    655      14    max
8  2026-05-02       A   east    612      77   jhon
9  2026-05-03       B   west    341      44    bob
10 2026-05-04       C  south    534      52  david
11 2026-05-05       D  north    720      20    max
12 2026-05-06       A   east    217      20   jhon
13 2026-05-07       B   west    163      31    bob
14 2026-05-08       C  south    868      86  david
15 2026-05-09       D  north    181      10    max
16 2026-05-10       A   east    796      47   jhon
17 2026-05-11       B   west    626      40    bob
18 2026-05-12       C  south    842      79  david
19 2026-05-13       D  north    745      27    max

In [11]:
df["month"] = df["date"].dt.month_name()
df["qourter"] = "Q" + df["date"].dt.quarter.astype(str)
df

         date product region  sales  unites    rep  month qourter
0  2026-04-24       A   east    383      41   jhon  April      Q2
1  2026-04-25       B   west    991      88    bob  April      Q2
2  2026-04-26       C  south    468      44  david  April      Q2
3  2026-04-27       D  north    326      45    max  April      Q2
4  2026-04-28       A   east    467      26   jhon  April      Q2
5  2026-04-29       B   west    966      23    bob  April      Q2
6  2026-04-30       C  south    855      45  david  April      Q2
7  2026-05-01       D  north    655      14    max    May      Q2
8  2026-05-02       A   east    612      77   jhon    May      Q2
9  2026-05-03       B   west    341      44    bob    May      Q2
10 2026-05-04       C  south    534      52  david    May      Q2
11 2026-05-05       D  north    720      20    max    May      Q2
12 2026-05-06       A   east    217      20   jhon    May      Q2
13 2026-05-07       B   west    163      31    bob    May      Q2
14 2026-05-08       C  south    868      86  david    May      Q2
15 2026-05-09       D  north    181      10    max    May      Q2
16 2026-05-10       A   east    796      47   jhon    May      Q2
17 2026-05-11       B   west    626      40    bob    May      Q2
18 2026-05-12       C  south    842      79  david    May      Q2
19 2026-05-13       D  north    745      27    max    May      Q2

In [12]:
pd.pivot_table(df,values= "sales",index= "region",columns= "product",)

product      A      B      C      D
region
east     495.0    NaN    NaN    NaN
north      NaN    NaN    NaN  525.4
south      NaN    NaN  713.4    NaN
west       NaN  617.4    NaN    NaN

#operation

In [13]:
df1 = pd.DataFrame({
    "A" : [1,2,3,4,5,6],
    "B" : [10,20,30,40,50,60],
    "C" : [100,200,300,400,500,600]
})

In [14]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
5  6  60  600

In [15]:
df.shape

(20, 8)

In [16]:
df.columns

Index(['date', 'product', 'region', 'sales', 'unites', 'rep', 'month',
       'qourter'],
      dtype='str')

In [17]:
df1.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
5  6  60  600>

In [18]:
df1["A"] + 12

0    13
1    14
2    15
3    16
4    17
5    18
Name: A, dtype: int64

In [19]:
def sq(x):
    return x**2

In [20]:
df1["C"].apply(sq) # use to apply any function on columns

0     10000
1     40000
2     90000
3    160000
4    250000
5    360000
Name: C, dtype: int64

In [21]:
df1["C"] = df1["C"].apply(sq)
df1

   A   B       C
0  1  10   10000
1  2  20   40000
2  3  30   90000
3  4  40  160000
4  5  50  250000
5  6  60  360000

In [22]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
        index=["skardu","shiger","khapolu","kharmang"],
        columns=["one","two","three","four"])

s1 = pd.Series(np.arange(5),index= ['a','b','c','d','e'])
s2 = pd.Series(np.arange(5),index=['a','b','c','g','h'])

data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15

In [24]:
data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15

In [25]:
data.iloc[0] # use for select row

one      0
two      1
three    2
four     3
Name: skardu, dtype: int64

In [26]:
data.iloc[0,[2]]  #use for multiple selection of row

three    2
Name: skardu, dtype: int64

In [27]:
#df.head() use for read first 5 rows and columns
#df.teil() use for read last rows and columns
#df.describe use for calculate data
#df.info use for to know data type of all values

In [28]:
data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15

In [29]:
data.max(axis=1)

skardu       3
shiger       7
khapolu     11
kharmang    15
dtype: int64

In [30]:
data.min(axis=1)

skardu       0
shiger       4
khapolu      8
kharmang    12
dtype: int64

In [31]:
data.mean(axis=1)

skardu       1.5
shiger       5.5
khapolu      9.5
kharmang    13.5
dtype: float64

In [32]:
s1+s2

a    0.0
b    2.0
c    4.0
d    NaN
e    NaN
g    NaN
h    NaN
dtype: float64

In [33]:
data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15

In [34]:
series = data.loc["skardu"]
series

one      0
two      1
three    2
four     3
Name: skardu, dtype: int64

In [35]:
data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15

In [36]:
data + series # series ka index and data fram ka index k saath match frir jo operation hamny likha hai wo apply hoga

          one  two  three  four
skardu      0    2      4     6
shiger      4    6      8    10
khapolu     8   10     12    14
kharmang   12   14     16    18

In [37]:
def fun1(s1):
    return s1.max()

In [38]:
data.apply(fun1)

one      12
two      13
three    14
four     15
dtype: int64

In [39]:
def fun2(s1):
    return pd.Series([s1.max(),s1.mean(),s1.min()],index=["max","mean","min"])

data.apply(fun2)

       one   two  three  four
max   12.0  13.0   14.0  15.0
mean   6.0   7.0    8.0   9.0
min    0.0   1.0    2.0   3.0

In [40]:
def fun4(x):
    return f"{x: .2f}" # use for 1f = . k bat 1 digit 2f mean . k bat 2 digit

d1 = pd.DataFrame(np.random.randn(5,5))
d1.map(fun4)

       0      1      2      3      4
0   0.39  -0.72  -1.35   1.03   1.00
1  -0.53  -0.72  -0.77   1.19  -0.83
2   0.99  -1.80  -1.01  -1.57  -0.67
3   1.12   1.20   0.50   0.38  -0.60
4  -0.59   1.53   0.09   0.83   0.26

In [45]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
        index=["skardu","shiger","khapolu","kharmang"],
        columns=["one","two","three","four"])


data

          one  two  three  four
skardu      0    1      2     3
shiger      4    5      6     7
khapolu     8    9     10    11
kharmang   12   13     14    15