In [35]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv("myfile.csv")

In [37]:
df.head()

   rank                                        title  score
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2

In [38]:
df.loc[1] #use for select any spacefic row

rank                                           2
title    money heist(ep 22)jan 2024 - jul 2013fk
score                                        9.3
Name: 1, dtype: object

In [39]:
df.loc[1] ["title"] #to select only row

'money heist(ep 22)jan 2024 - jul 2013fk'

In [40]:
def extract(txt): # this is a function which will seprate only inside the bracket values mean here the value is epsode number
    check = False
    data = ""
    for ch in txt:
        if ch == ")":
            check = False
            break
            return data
        if check == True:
            data = data + ch
        if ch == "(":
            check = True
            
    return data

In [41]:
df["title"].apply(extract)

0    ep 12
1    ep 22
2    ep 44
3    ep 33
4    ep 15
Name: title, dtype: str

In [42]:
df["Epesode"] = df["title"].apply(extract)
df

   rank                                        title  score Epesode
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4   ep 12
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3   ep 22
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0   ep 44
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6   ep 33
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2   ep 15

In [43]:
df["Epesode"] = df["Epesode"].str.replace("ep ","")
df

   rank                                        title  score Epesode
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4      12
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3      22
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0      44
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6      33
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2      15

In [44]:
df["Epesode"] = df["Epesode"].astype(int) #use to convert str value into int type
df

   rank                                        title  score  Epesode
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4       12
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3       22
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0       44
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6       33
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2       15

In [45]:
df

   rank                                        title  score  Epesode
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4       12
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3       22
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0       44
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6       33
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2       15

In [46]:
def extract_time(dat):
    check = False
    time = ""
    count = 0
    for ch in dat:
        if ch == ")":
            check = True
        if check == True:
            time = time + ch
            count += 1
        if count == 19:
            check = False
            break
                
    return time

In [47]:
df

   rank                                        title  score  Epesode
0     1   game of throne(ep 12)apr 2025 - mar 2023dj    9.4       12
1     2      money heist(ep 22)jan 2024 - jul 2013fk    9.3       22
2     3    breaking bad(ep 44)may 2013 - dec 2016ddd    9.0       44
3     4          avatar(ep 33)june 2026 - feb 2018ee    6.6       33
4     5  stranger things(ep 15)nov 2023 - sep 2019yh    9.2       15

In [48]:
df["Time stampe"] = df["title"].apply(extract_time)
df

,rank,title,score,Epesode,Time stampe
0,1,game of throne(ep 12)apr 2025 - mar 2023dj,9.4,12,)apr 2025 - mar 202
1,2,money heist(ep 22)jan 2024 - jul 2013fk,9.3,22,)jan 2024 - jul 201
2,3,breaking bad(ep 44)may 2013 - dec 2016ddd,9.0,44,)may 2013 - dec 201
3,4,avatar(ep 33)june 2026 - feb 2018ee,6.6,33,)june 2026 - feb 20
4,5,stranger things(ep 15)nov 2023 - sep 2019yh,9.2,15,)nov 2023 - sep 201

In [49]:
df["Time stampe"] = df["Time stampe"].str.replace(")","")
df

,rank,title,score,Epesode,Time stampe
0,1,game of throne(ep 12)apr 2025 - mar 2023dj,9.4,12,apr 2025 - mar 202
1,2,money heist(ep 22)jan 2024 - jul 2013fk,9.3,22,jan 2024 - jul 201
2,3,breaking bad(ep 44)may 2013 - dec 2016ddd,9.0,44,may 2013 - dec 201
3,4,avatar(ep 33)june 2026 - feb 2018ee,6.6,33,june 2026 - feb 20
4,5,stranger things(ep 15)nov 2023 - sep 2019yh,9.2,15,nov 2023 - sep 201

In [50]:
df[df["score"] == df["score"].max() ]

,rank,title,score,Epesode,Time stampe
0,1,game of throne(ep 12)apr 2025 - mar 2023dj,9.4,12,apr 2025 - mar 202

In [51]:
df[df["Epesode"] == df["Epesode"].max()]

,rank,title,score,Epesode,Time stampe
2,3,breaking bad(ep 44)may 2013 - dec 2016ddd,9.0,44,may 2013 - dec 201

In [52]:
df

,rank,title,score,Epesode,Time stampe
0,1,game of throne(ep 12)apr 2025 - mar 2023dj,9.4,12,apr 2025 - mar 202
1,2,money heist(ep 22)jan 2024 - jul 2013fk,9.3,22,jan 2024 - jul 201
2,3,breaking bad(ep 44)may 2013 - dec 2016ddd,9.0,44,may 2013 - dec 201
3,4,avatar(ep 33)june 2026 - feb 2018ee,6.6,33,june 2026 - feb 20
4,5,stranger things(ep 15)nov 2023 - sep 2019yh,9.2,15,nov 2023 - sep 201

In [53]:
def remve(x):
    check = True
    name = ""
    for ch in x:
        if check == True:
                if ch == "(":
                     break
                name = name + ch

    return name

In [54]:
df["title"].apply(remve)

0     game of throne
1        money heist
2       breaking bad
3             avatar
4    stranger things
Name: title, dtype: str

In [55]:
df["title"]= df["title"].apply(remve)
df

   rank            title  score  Epesode         Time stampe
0     1   game of throne    9.4       12  apr 2025 - mar 202
1     2      money heist    9.3       22  jan 2024 - jul 201
2     3     breaking bad    9.0       44  may 2013 - dec 201
3     4           avatar    6.6       33  june 2026 - feb 20
4     5  stranger things    9.2       15  nov 2023 - sep 201

In [56]:
df["Time stampe"] = df["Time stampe"].replace("(","")

In [58]:
df

   rank            title  score  Epesode         Time stampe
0     1   game of throne    9.4       12  apr 2025 - mar 202
1     2      money heist    9.3       22  jan 2024 - jul 201
2     3     breaking bad    9.0       44  may 2013 - dec 201
3     4           avatar    6.6       33  june 2026 - feb 20
4     5  stranger things    9.2       15  nov 2023 - sep 201

In [62]:
df.sort_values(["score"],ascending=False)

   rank            title  score  Epesode         Time stampe
0     1   game of throne    9.4       12  apr 2025 - mar 202
1     2      money heist    9.3       22  jan 2024 - jul 201
4     5  stranger things    9.2       15  nov 2023 - sep 201
2     3     breaking bad    9.0       44  may 2013 - dec 201
3     4           avatar    6.6       33  june 2026 - feb 20

In [2]:
import pygame

pygame-ce 2.5.8 (SDL 2.32.10, Python 3.13.14)