In [42]:
import numpy as np 
import pandas as pd

In [43]:
data_1 = pd.DataFrame({
    "employ_name" : ['A','B','C','D','E'],
    "age" : [12,16,19,27,20],
    "city" : ["karachi","gb","islamabad","panjab","skardu"]
})

data_2 = pd.DataFrame({
    "employ_name" : ["ali","muhammad","ahmad","javid","musa"],
    "salary" : [1200,16000,19000,35000,20000],
    "gender" : ["male","male","male","femail","femail"]
   
})

In [44]:
print(data_1)

  employ_name  age       city
0           A   12    karachi
1           B   16         gb
2           C   19  islamabad
3           D   27     panjab
4           E   20     skardu

In [45]:
print(data_2)

  employ_name  salary  gender
0         ali    1200    male
1    muhammad   16000    male
2       ahmad   19000    male
3       javid   35000  femail
4        musa   20000  femail

In [46]:
#now we are marging two data frme
pd.merge(data_1,data_2)

Empty DataFrame
Columns: [employ_name, age, city, salary, gender]
Index: []

In [47]:
import numpy as np 
import pandas as pd

In [48]:
data = ({
    "name" : ["ali","hassan","muhammad","muzammil","shakir"],
    "age" : [12,16,19,27,20],
    "com_marks" : [90,28,44,55,77],
    "math_marks" : [99,22,37,88,99]
})

df = pd.DataFrame(data,index=[1,2,3,4,5])
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [49]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [50]:
df.name

1         ali
2      hassan
3    muhammad
4    muzammil
5      shakir
Name: name, dtype: str

In [51]:
df[["name","age"]] # for print  multiple values

       name  age
1       ali   12
2    hassan   16
3  muhammad   19
4  muzammil   27
5    shakir   20

In [52]:
df["name"] #for print single coloms

1         ali
2      hassan
3    muhammad
4    muzammil
5      shakir
Name: name, dtype: str

In [53]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [54]:
df.columns #use for check coloms

Index(['name', 'age', 'com_marks', 'math_marks'], dtype='str')

In [55]:
df.index #use for print index

Index([1, 2, 3, 4, 5], dtype='int64')

In [56]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [57]:
df.reindex(index=(3,2,1,4)) #use for mix /suffle

       name  age  com_marks  math_marks
3  muhammad   19         44          37
2    hassan   16         28          22
1       ali   12         90          99
4  muzammil   27         55          88

In [58]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [59]:
df.reindex(index=(1,3,2,4,5,6)) #if not index is our data mean list it will automatically print next roww with null valued

       name   age  com_marks  math_marks
1       ali  12.0       90.0        99.0
3  muhammad  19.0       44.0        37.0
2    hassan  16.0       28.0        22.0
4  muzammil  27.0       55.0        88.0
5    shakir  20.0       77.0        99.0
6       NaN   NaN        NaN         NaN

In [60]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [61]:
df.reindex(columns=("name","com_marks")) #use for random

       name  com_marks
1       ali         90
2    hassan         28
3  muhammad         44
4  muzammil         55
5    shakir         77

In [62]:
df

       name  age  com_marks  math_marks
1       ali   12         90          99
2    hassan   16         28          22
3  muhammad   19         44          37
4  muzammil   27         55          88
5    shakir   20         77          99

In [63]:
df2 = df.drop(columns=["name"]) # use for delete any colomns
df2

   age  com_marks  math_marks
1   12         90          99
2   16         28          22
3   19         44          37
4   27         55          88
5   20         77          99

In [71]:
df.drop(columns=["com_marks"],inplace=True) #for remove col from orignal data

In [72]:
df

       name  age
1       ali   12
2    hassan   16
3  muhammad   19
4  muzammil   27
5    shakir   20

In [ ]:
df["math_marks"] = [99,98,70,60,89] #for add any colomn in data
df

       name  age  math_marks
1       ali   12          99
2    hassan   16          98
3  muhammad   19          70
4  muzammil   27          60
5    shakir   20          89

In [77]:
df2

   age  com_marks  math_marks
1   12         90          99
2   16         28          22
3   19         44          37
4   27         55          88
5   20         77          99

In [79]:
df2["persentage"] = (df["math_marks"]/200)*100

In [80]:
df2

   age  com_marks  math_marks  persentage
1   12         90          99        49.5
2   16         28          22        49.0
3   19         44          37        35.0
4   27         55          88        30.0
5   20         77          99        44.5

In [81]:
df

       name  age  math_marks
1       ali   12          99
2    hassan   16          98
3  muhammad   19          70
4  muzammil   27          60
5    shakir   20          89

In [82]:
df["total"] = ((df2["com_marks"] + df["math_marks"])/200)*100

In [83]:
df

       name  age  math_marks  total
1       ali   12          99   94.5
2    hassan   16          98   63.0
3  muhammad   19          70   57.0
4  muzammil   27          60   57.5
5    shakir   20          89   83.0

In [84]:
df2

   age  com_marks  math_marks  persentage
1   12         90          99        49.5
2   16         28          22        49.0
3   19         44          37        35.0
4   27         55          88        30.0
5   20         77          99        44.5

In [ ]:
df2[df2["persentage"] >= 40] #use for add  that student have more than 40 persentage

   age  com_marks  math_marks  persentage
1   12         90          99        49.5
2   16         28          22        49.0
5   20         77          99        44.5

In [ ]:
my_list = [16,20]

df2[df2["age"].isin (my_list)] #check for only which age in our new list mean mylist

   age  com_marks  math_marks  persentage
2   16         28          22        49.0
5   20         77          99        44.5