#pandas practice

In [314]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [315]:
data = pd.read_csv("C:\\data\\titanic.csv")
data

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [316]:
data.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"

In [317]:
data.tail(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1299,3,0,"Yasbeck, Mr. Antoni",male,27,1,0,2659,14.4542,?,C,C,?,?
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15,1,0,2659,14.4542,?,C,?,?,?
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,?,C,?,312,?
1302,3,0,"Yousif, Mr. Wazli",male,?,0,0,2647,7.225,?,C,?,?,?
1303,3,0,"Yousseff, Mr. Gerious",male,?,0,0,2627,14.4583,?,C,?,?,?
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [318]:
data["pclass"].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [319]:
data["pclass"].value_counts(normalize=True)

pclass
3    0.541635
1    0.246753
2    0.211612
Name: proportion, dtype: float64

In [320]:
data[data["pclass"] == 3] # with the help of this method we can see only the people whos num is 3

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
600,3,0,"Abbing, Mr. Anthony",male,42,0,0,C.A. 5547,7.55,?,S,?,?,?
601,3,0,"Abbott, Master. Eugene Joseph",male,13,0,2,C.A. 2673,20.25,?,S,?,?,"East Providence, RI"
602,3,0,"Abbott, Mr. Rossmore Edward",male,16,1,1,C.A. 2673,20.25,?,S,?,190,"East Providence, RI"
603,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35,1,1,C.A. 2673,20.25,?,S,A,?,"East Providence, RI"
604,3,1,"Abelseth, Miss. Karen Marie",female,16,0,0,348125,7.65,?,S,16,?,"Norway Los Angeles, CA"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [321]:
data["pclass name"] = data["pclass"].map({1:"first",2:"second",3:"third"})

In [322]:
data.groupby("pclass")["survived"].mean() * 100

pclass
1    61.919505
2    42.960289
3    25.528914
Name: survived, dtype: float64

In [323]:
data = data.rename(columns={"pclass" : "P-Class","name" : "Name"})
data

,P-Class,survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,third

In [324]:
data["P-Class"].value_counts()

P-Class
3    709
1    323
2    277
Name: count, dtype: int64

In [325]:
data.groupby("P-Class")["survived"].mean() *100

P-Class
1    61.919505
2    42.960289
3    25.528914
Name: survived, dtype: float64

In [326]:
data = data.rename(columns={"survived" : "Survived"})
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,third

In [327]:
data.groupby("sex")["Survived"].mean() * 100

sex
female    72.746781
male      19.098458
Name: Survived, dtype: float64

In [328]:
data["Survived"].value_counts()

Survived
0    809
1    500
Name: count, dtype: int64

In [329]:
data["Survived"].value_counts(normalize=True) * 100

Survived
0    61.802903
1    38.197097
Name: proportion, dtype: float64

In [330]:
data["type"]

KeyError: 'type'

In [ ]:
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,type
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,alive
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,alive
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,death
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,death
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,death
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third,death
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third,death
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third,death
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?,third,death
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,third,death

In [ ]:
data["f-name"] = data["sex"].map({"female" : data["Name"],"male" : "None"})
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,f-name
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,"0 Allen, Miss. Elisabe..."
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,None
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,"0 Allen, Miss. Elisabe..."
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,None
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,"0 Allen, Miss. Elisabe..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third,"0 Allen, Miss. Elisabe..."
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third,"0 Allen, Miss. Elisabe..."
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third,None
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?,third,None
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,third,None

In [ ]:
data["M-name"] = data["sex"].map({"male":data["Name"],"female" : "None"})
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,f-name,M-name
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,"0 Allen, Miss. Elisabe...",None
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,None,"0 Allen, Miss. Elisabe..."
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,"0 Allen, Miss. Elisabe...",None
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,None,"0 Allen, Miss. Elisabe..."
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,"0 Allen, Miss. Elisabe...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third,"0 Allen, Miss. Elisabe...",None
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third,"0 Allen, Miss. Elisabe...",None
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third,None,"0 Allen, Miss. Elisabe..."
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?,third,None,"0 Allen, Miss. Elisabe..."
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?,third,None,"0 Allen, Miss. Elisabe..."

In [ ]:
data["sex"].value_counts()

sex
male      843
female    466
Name: count, dtype: int64

In [ ]:
data["sex"] = data["sex"].replace({"female":"F","male":"M"})
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",F,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",M,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",F,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",M,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",F,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",F,14.5,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",F,?,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",M,26.5,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",M,27,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",M,29,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",F,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",M,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",F,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",M,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",F,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",F,14.5,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",F,?,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",M,26.5,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",M,27,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",M,29,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data["age"] = data["age"].replace("?",pd.NA)
data["age"] = data["age"].astype("float")

In [ ]:
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",F,29.0000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",M,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",F,2.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",M,30.0000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",F,25.0000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",F,14.5000,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",F,NaN,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",M,26.5000,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",M,27.0000,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",M,29.0000,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data.tail()

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data["age"].describe()

count    1046.000000
mean       29.881135
std        14.413500
min         0.166700
25%        21.000000
50%        28.000000
75%        39.000000
max        80.000000
Name: age, dtype: float64

In [ ]:
data["age"].fillna(data["age"].mean(),inplace=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_6556\3250616897.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data["age"].fillna(data["age"].mean(),inplace=True)

0       29.000000
1        0.916700
2        2.000000
3       30.000000
4       25.000000
          ...
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1309, dtype: float64

In [ ]:
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first
1,1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first
2,1,0,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data.tail(16)

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name
1293,3,0,"Williams, Mr. Howard Hugh 'Harry'",male,29.881135,0,0,A/5 2466,8.05,?,S,?,?,?,third
1294,3,0,"Williams, Mr. Leslie",male,28.500000,0,0,54636,16.1,?,S,?,14,?,third
1295,3,0,"Windelov, Mr. Einar",male,21.000000,0,0,SOTON/OQ 3101317,7.25,?,S,?,?,?,third
1296,3,0,"Wirz, Mr. Albert",male,27.000000,0,0,315154,8.6625,?,S,?,131,?,third
1297,3,0,"Wiseman, Mr. Phillippe",male,29.881135,0,0,A/4. 34244,7.25,?,S,?,?,?,third
1298,3,0,"Wittevrongel, Mr. Camille",male,36.000000,0,0,345771,9.5,?,S,?,?,?,third
1299,3,0,"Yasbeck, Mr. Antoni",male,27.000000,1,0,2659,14.4542,?,C,C,?,?,third
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.000000,1,0,2659,14.4542,?,C,?,?,?,third
1301,3,0,"Youseff, Mr. Gerious",male,45.500000,0,0,2628,7.225,?,C,?,312,?,third
1302,3,0,"Yousif, Mr. Wazli",male,29.881135,0,0,2647,7.225,?,C,?,?,?,third
1303,3,0,"Yousseff, Mr. Gerious",male,29.881135,0,0,2627,14.4583,?,C,?,?,?,third
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third

In [ ]:
data["age"].value_counts()

age
29.881135    263
24.000000     47
22.000000     43
21.000000     41
30.000000     40
            ...
60.500000      1
74.000000      1
0.416700       1
11.500000      1
26.500000      1
Name: count, Length: 99, dtype: int64

In [ ]:
data["age"].describe()

count    1309.000000
mean       29.881135
std        12.883199
min         0.166700
25%        22.000000
50%        29.881135
75%        35.000000
max        80.000000
Name: age, dtype: float64

In [ ]:
data["age"].min()

np.float64(0.1667)

In [ ]:
data["age"].median()

np.float64(29.8811345124283)

In [ ]:
bins = [0,12,18,40,80]
labels = ["kids","teenagers","adult","old main"]
data["age group"] = pd.cut(data["age"],bins=bins ,labels=labels)
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,age group
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,adult
1,1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,kids
2,1,0,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,kids
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,adult
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third,teenagers
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third,adult
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third,adult
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third,adult
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third,adult

In [ ]:
data.tail(20)

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,age group
1289,3,0,"Wiklund, Mr. Karl Johan",male,21.000000,1,0,3101266,6.4958,?,S,?,?,?,third,adult
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.000000,1,0,363272,7,?,S,?,?,?,third,old main
1291,3,0,"Willer, Mr. Aaron ('Abi Weller')",male,29.881135,0,0,3410,8.7125,?,S,?,?,?,third,adult
1292,3,0,"Willey, Mr. Edward",male,29.881135,0,0,S.O./P.P. 751,7.55,?,S,?,?,?,third,adult
1293,3,0,"Williams, Mr. Howard Hugh 'Harry'",male,29.881135,0,0,A/5 2466,8.05,?,S,?,?,?,third,adult
1294,3,0,"Williams, Mr. Leslie",male,28.500000,0,0,54636,16.1,?,S,?,14,?,third,adult
1295,3,0,"Windelov, Mr. Einar",male,21.000000,0,0,SOTON/OQ 3101317,7.25,?,S,?,?,?,third,adult
1296,3,0,"Wirz, Mr. Albert",male,27.000000,0,0,315154,8.6625,?,S,?,131,?,third,adult
1297,3,0,"Wiseman, Mr. Phillippe",male,29.881135,0,0,A/4. 34244,7.25,?,S,?,?,?,third,adult
1298,3,0,"Wittevrongel, Mr. Camille",male,36.000000,0,0,345771,9.5,?,S,?,?,?,third,adult
1299,3,0,"Yasbeck, Mr. Antoni",male,27.000000,1,0,2659,14.4542,?,C,C,?,?,third,adult
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.000000,1,0,2659,14.4542,?,C,?,?,?,third,teenagers
1301,3,0,"Youseff, Mr. Gerious",male,45.500000,0,0,2628,7.225,?,C,?,312,?,third,old main
1302,3,0,"Yousif, Mr. Wazli",male,29.881135,0,0,2647,7.225,?,C,?,?,?,third,adult
1303,3,0,"Yousseff, Mr. Gerious",male,29.881135,0,0,2627,14.4583,?,C,?,?,?,third,adult
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third,teenagers
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third,adult
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third,adult
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third,adult
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third,adult

In [ ]:
data["travel types"] = data["sibsp"].apply(lambda x : "alone" if x==0 else "with faimly" )
data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,age group,travel types
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,adult,alone
1,1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,kids,with faimly
2,1,0,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,kids,with faimly
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,adult,with faimly
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,adult,with faimly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third,teenagers,with faimly
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third,adult,with faimly
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third,adult,alone
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third,adult,alone
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third,adult,alone

In [ ]:
data.tail(8)

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,age group,travel types
1301,3,0,"Youseff, Mr. Gerious",male,45.500000,0,0,2628,7.225,?,C,?,312,?,third,old main,alone
1302,3,0,"Yousif, Mr. Wazli",male,29.881135,0,0,2647,7.225,?,C,?,?,?,third,adult,alone
1303,3,0,"Yousseff, Mr. Gerious",male,29.881135,0,0,2627,14.4583,?,C,?,?,?,third,adult,alone
1304,3,0,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,?,C,?,328,?,third,teenagers,with faimly
1305,3,0,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,?,C,?,?,?,third,adult,with faimly
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.225,?,C,?,304,?,third,adult,alone
1307,3,0,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.225,?,C,?,?,?,third,adult,alone
1308,3,0,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.875,?,S,?,?,?,third,adult,alone

In [ ]:
data["sibsp"].mean()

np.float64(0.4988540870893812)

In [ ]:
data["sibsp"].value_counts()

sibsp
0    891
1    319
2     42
4     22
3     20
8      9
5      6
Name: count, dtype: int64

In [ ]:
data[data["sibsp"] > 7]

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,age group,travel types
1170,3,0,"Sage, Master. Thomas Henry",male,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1171,3,0,"Sage, Master. William Henry",male,14.500000,8,2,CA. 2343,69.55,?,S,?,67,?,third,teenagers,with faimly
1172,3,0,"Sage, Miss. Ada",female,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1173,3,0,"Sage, Miss. Constance Gladys",female,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1174,3,0,"Sage, Miss. Dorothy Edith 'Dolly'",female,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1175,3,0,"Sage, Miss. Stella Anna",female,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1176,3,0,"Sage, Mr. Douglas Bullen",male,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1177,3,0,"Sage, Mr. Frederick",male,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly
1178,3,0,"Sage, Mr. George John Jr",male,29.881135,8,2,CA. 2343,69.55,?,S,?,?,?,third,adult,with faimly

In [ ]:
data["parch"].value_counts()

parch
0    1002
1     170
2     113
3       8
4       6
5       6
6       2
9       2
Name: count, dtype: int64

In [ ]:
data["parch"].describe()

count    1309.000000
mean        0.385027
std         0.865560
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         9.000000
Name: parch, dtype: float64

In [ ]:
data["ticket"].value_counts()

ticket
CA. 2343        11
1601             8
CA 2144          8
PC 17608         7
S.O.C. 14879     7
                ..
2628             1
2647             1
2656             1
2670             1
315082           1
Name: count, Length: 929, dtype: int64

In [331]:
data.fillna(data["fare"].mean(),inplace=True)

TypeError: Cannot perform reduction 'mean' with string dtype

In [334]:
data[data["fare"] == pd.NA]

Empty DataFrame
Columns: [P-Class, Survived, Name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest, pclass name]
Index: []

In [ ]:
binz = [0,10,30,50,100]
labelz = ["sasta","normal price","mhenga","thora mhenga"]

data["group of prices"] = pd.cut(data["fare"],bins=binz ,labels=labelz)

data

,P-Class,Survived,Name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,pclass name,group of prices
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO",first,NaN
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON",first,NaN
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.5500,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,NaN
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.5500,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON",first,NaN
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.5500,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON",first,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?,third,normal price
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?,third,normal price
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,?,C,?,304,?,third,sasta
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.2250,?,C,?,?,?,third,sasta
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.8750,?,S,?,?,?,third,sasta

In [1]:
import pygame

pygame-ce 2.5.8 (SDL 2.32.10, Python 3.13.14)