#titanic data set

In [497]:
import numpy as np 
import pandas as pd

In [498]:
titanic =pd.read_csv("C:\\data\\titanic.csv")
titanic.shape# to show first 10 rows of data

(1309, 14)

In [499]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1309 non-null   str
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: int64(4), str(10)
memory usage: 143.3 KB

In [500]:
titanic.describe()

            pclass     survived        sibsp        parch
count  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882     0.381971     0.498854     0.385027
std       0.837836     0.486055     1.041658     0.865560
min       1.000000     0.000000     0.000000     0.000000
25%       2.000000     0.000000     0.000000     0.000000
50%       3.000000     0.000000     0.000000     0.000000
75%       3.000000     1.000000     1.000000     0.000000
max       3.000000     1.000000     8.000000     9.000000

In [501]:
titanic.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"

In [502]:
titanic.tail(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1299,3,0,"Yasbeck, Mr. Antoni",male,27,1,0,2659,14.4542,?,C,C,?,?
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15,1,0,2659,14.4542,?,C,?,?,?
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.225,?,C,?,312,?
1302,3,0,"Yousif, Mr. Wazli",male,?,0,0,2647,7.225,?,C,?,?,?
1303,3,0,"Yousseff, Mr. Gerious",male,?,0,0,2627,14.4583,?,C,?,?,?
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,?,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,27,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,29,0,0,315082,7.875,?,S,?,?,?

In [503]:
titanic[titanic["ticket"] == titanic["ticket"].max()]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
81,1,0,"Crosby, Capt. Edward Gifford",male,70,1,1,WE/P 5735,71,B22,S,?,269,"Milwaukee, WI"
82,1,1,"Crosby, Miss. Harriet R",female,36,0,2,WE/P 5735,71,B22,S,7,?,"Milwaukee, WI"

In [504]:
titanic["ticket"].sort_index()

0        24160
1       113781
2       113781
3       113781
4       113781
         ...
1304      2665
1305      2665
1306      2656
1307      2670
1308    315082
Name: ticket, Length: 1309, dtype: str

In [505]:
titanic =pd.read_csv("C:\\data\\titanic.csv")
titanic.shape# to show first 10 rows of data

(1309, 14)

In [506]:
titanic.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"

In [507]:
d1 = pd.DataFrame({
    "name" :["ali",None,"ahmad","shahid","shakir"],
    "age" : [11,33,5,None,None],
    "marks" : [22,77,None,55,88]
})

d1.isna().sum() #use to find

name     1
age      2
marks    1
dtype: int64

In [508]:
d2 = d1.copy()
d2

     name   age  marks
0     ali  11.0   22.0
1     NaN  33.0   77.0
2   ahmad   5.0    NaN
3  shahid   NaN   55.0
4  shakir   NaN   88.0

In [509]:
d2.fillna(0) #fill miss data with 0

     name   age  marks
0     ali  11.0   22.0
1       0  33.0   77.0
2   ahmad   5.0    0.0
3  shahid   0.0   55.0
4  shakir   0.0   88.0

In [510]:
mean_age = d2["age"].mean()
mean_marks = d2["marks"].mean()
d2.fillna({"name":"unknown","age":mean_age,"marks":mean_marks})

      name        age  marks
0      ali  11.000000   22.0
1  unknown  33.000000   77.0
2    ahmad   5.000000   60.5
3   shahid  16.333333   55.0
4   shakir  16.333333   88.0

In [511]:
d1.dropna(thresh=2)

     name   age  marks
0     ali  11.0   22.0
1     NaN  33.0   77.0
2   ahmad   5.0    NaN
3  shahid   NaN   55.0
4  shakir   NaN   88.0

In [512]:
titanic.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"

In [513]:
#titanic[titanic]["sex"]==["female"]["fare"].sum()

In [514]:
titanic.groupby("sex")["fare"].sum()

sex
female    211.3375151.55151.5577.958351.4792227.52569.37...
male      151.55151.5526.55049.5042227.5253025.925247.52...
Name: fare, dtype: str

In [515]:
titanic["sex"]= titanic["sex"].replace({"femail":"F","mail":"M"})

In [516]:
df4 = pd.DataFrame({
    "name" :["ali",None,"ahmad","shahid","shakir"],
    "age" : [11,33,5,None,None],
    "marks" : [22,77,None,55,88],
    "gender" : ["male","female","male","female","male"]
})
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [517]:
df4.head(3) #its use for top rows

    name   age  marks  gender
0    ali  11.0   22.0    male
1    NaN  33.0   77.0  female
2  ahmad   5.0    NaN    male

In [518]:
df4.tail(3) #its use for last rows

     name  age  marks  gender
2   ahmad  5.0    NaN    male
3  shahid  NaN   55.0  female
4  shakir  NaN   88.0    male

In [519]:
df4.shape

(5, 4)

In [520]:
print("number of rows:",df4.shape)

number of rows: (5, 4)

In [521]:
df4.describe() # it is use only to show numerical values

             age      marks
count   3.000000   4.000000
mean   16.333333  60.500000
std    14.742230  29.103264
min     5.000000  22.000000
25%     8.000000  46.750000
50%    11.000000  66.000000
75%    22.000000  79.750000
max    33.000000  88.000000

In [522]:
df4.describe(include="all") # and this one is used for to shoe all the values

       name        age      marks gender
count     4   3.000000   4.000000      5
unique    4        NaN        NaN      2
top     ali        NaN        NaN   male
freq      1        NaN        NaN      3
mean    NaN  16.333333  60.500000    NaN
std     NaN  14.742230  29.103264    NaN
min     NaN   5.000000  22.000000    NaN
25%     NaN   8.000000  46.750000    NaN
50%     NaN  11.000000  66.000000    NaN
75%     NaN  22.000000  79.750000    NaN
max     NaN  33.000000  88.000000    NaN

In [523]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [524]:
df4["gender"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [525]:
df4["gender"].nunique() # it is use for to check the number of unique value in specific way

2

In [526]:
df4["gender"].value_counts() #this method is use for to check the count value of unique valyes

gender
male      3
female    2
Name: count, dtype: int64

In [527]:
df4["marks"]

0    22.0
1    77.0
2     NaN
3    55.0
4    88.0
Name: marks, dtype: float64

In [528]:
df4["marks"]>= 80

0    False
1    False
2    False
3    False
4     True
Name: marks, dtype: bool

In [529]:
df4[df4["marks"]>= 80] # it will print only the rows which is more than 80

     name  age  marks gender
4  shakir  NaN   88.0   male

In [530]:
df4[(df4["marks"] >= 80) & (df4["marks"] <= 100)] # to care about brakects in this case

     name  age  marks gender
4  shakir  NaN   88.0   male

In [531]:
total_std_with_90 = len(df4[(df4["marks"] >= 80) & (df4["marks"] <= 100)])

In [532]:
print("total students which score is more than 90 and less than 100 :",total_std_with_90)

total students which score is more than 90 and less than 100 : 1

In [533]:
#2nd method to do the same thing
df4["marks"].between(80,100)

0    False
1    False
2    False
3    False
4     True
Name: marks, dtype: bool

In [534]:
sum(df4["marks"].between(80,100)) # it will return the std count valuse
#which marks is greater
#than 90 and less than 100

1

In [535]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [536]:
df4["marks"].mean()

np.float64(60.5)

In [537]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [538]:
df4["marks"].fillna(df4["marks"].mean())

0    22.0
1    77.0
2    60.5
3    55.0
4    88.0
Name: marks, dtype: float64

In [539]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [540]:
df4["age"].fillna(df4["age"].mean())

0    11.000000
1    33.000000
2     5.000000
3    16.333333
4    16.333333
Name: age, dtype: float64

In [541]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [542]:
df4["name"]= df4["name"].astype(str)
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [543]:
df4["name"]

0       ali
1       NaN
2     ahmad
3    shahid
4    shakir
Name: name, dtype: str

In [544]:
df4["gender"].map({"male":"M","female":"F"})

0    M
1    F
2    M
3    F
4    M
Name: gender, dtype: str

In [545]:
df4

     name   age  marks  gender
0     ali  11.0   22.0    male
1     NaN  33.0   77.0  female
2   ahmad   5.0    NaN    male
3  shahid   NaN   55.0  female
4  shakir   NaN   88.0    male

In [546]:
df4["new gender"] = df4["gender"].map({"male":"M","female":"F"})
df4

     name   age  marks  gender new gender
0     ali  11.0   22.0    male          M
1     NaN  33.0   77.0  female          F
2   ahmad   5.0    NaN    male          M
3  shahid   NaN   55.0  female          F
4  shakir   NaN   88.0    male          M

In [547]:
df4["gender in number"] = df4["gender"].map({"male":1,"female":0})
df4

     name   age  marks  gender new gender  gender in number
0     ali  11.0   22.0    male          M                 1
1     NaN  33.0   77.0  female          F                 0
2   ahmad   5.0    NaN    male          M                 1
3  shahid   NaN   55.0  female          F                 0
4  shakir   NaN   88.0    male          M                 1

In [548]:
df4

     name   age  marks  gender new gender  gender in number
0     ali  11.0   22.0    male          M                 1
1     NaN  33.0   77.0  female          F                 0
2   ahmad   5.0    NaN    male          M                 1
3  shahid   NaN   55.0  female          F                 0
4  shakir   NaN   88.0    male          M                 1

In [549]:
df4= df4.drop("gender in number",axis=1)
df4

     name   age  marks  gender new gender
0     ali  11.0   22.0    male          M
1     NaN  33.0   77.0  female          F
2   ahmad   5.0    NaN    male          M
3  shahid   NaN   55.0  female          F
4  shakir   NaN   88.0    male          M

In [550]:
df4

     name   age  marks  gender new gender
0     ali  11.0   22.0    male          M
1     NaN  33.0   77.0  female          F
2   ahmad   5.0    NaN    male          M
3  shahid   NaN   55.0  female          F
4  shakir   NaN   88.0    male          M

In [551]:
df4 = df4.drop(["age","new gender"],axis=1)
df4

     name  marks  gender
0     ali   22.0    male
1     NaN   77.0  female
2   ahmad    NaN    male
3  shahid   55.0  female
4  shakir   88.0    male

In [552]:
df4

     name  marks  gender
0     ali   22.0    male
1     NaN   77.0  female
2   ahmad    NaN    male
3  shahid   55.0  female
4  shakir   88.0    male

In [553]:
df4.columns

Index(['name', 'marks', 'gender'], dtype='str')

In [554]:
df4.index

RangeIndex(start=0, stop=5, step=1)

In [555]:
df4

     name  marks  gender
0     ali   22.0    male
1     NaN   77.0  female
2   ahmad    NaN    male
3  shahid   55.0  female
4  shakir   88.0    male

In [556]:
df4.sort_values(by="marks") # sort in ascending order

     name  marks  gender
0     ali   22.0    male
3  shahid   55.0  female
1     NaN   77.0  female
4  shakir   88.0    male
2   ahmad    NaN    male

In [557]:
df4.sort_values(by="marks",ascending=False) # desending order

     name  marks  gender
4  shakir   88.0    male
1     NaN   77.0  female
3  shahid   55.0  female
0     ali   22.0    male
2   ahmad    NaN    male

In [558]:
df4.sort_values(by=["marks","gender","name"],ascending=False) # sort for multiple at once
df4

     name  marks  gender
0     ali   22.0    male
1     NaN   77.0  female
2   ahmad    NaN    male
3  shahid   55.0  female
4  shakir   88.0    male

In [559]:
df4["gender"]

0      male
1    female
2      male
3    female
4      male
Name: gender, dtype: str

In [560]:
df4["gender"] == "female"

0    False
1     True
2    False
3     True
4    False
Name: gender, dtype: bool

In [561]:
df4[df4["gender"] == "female"] [["name","marks"]]

     name  marks
1     NaN   77.0
3  shahid   55.0

In [562]:
df4["gender"].isin(["female"])

0    False
1     True
2    False
3     True
4    False
Name: gender, dtype: bool

In [563]:
df4[df4["gender"].isin(["female"])] [["name","marks"]]

     name  marks
1     NaN   77.0
3  shahid   55.0

In [564]:
titanic =pd.read_csv("C:\\data\\titanic.csv")

In [565]:
titanic.shape

(1309, 14)

In [566]:
titanic.index

RangeIndex(start=0, stop=1309, step=1)

In [567]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='str')

In [568]:
titanic.head(15)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48,0,0,19952,26.55,E12,S,3,?,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,D7,S,10,?,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39,0,0,112050,0,A36,S,?,?,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53,2,0,11769,51.4792,C101,S,D,?,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71,0,0,PC 17609,49.5042,?,C,?,22,"Montevideo, Uruguay"
10,1,0,"Astor, Col. John Jacob",male,47,1,0,PC 17757,227.525,C62 C64,C,?,124,"New York, NY"
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18,1,0,PC 17757,227.525,C62 C64,C,4,?,"New York, NY"
12,1,1,"Aubart, Mme. Leontine Pauline",female,24,0,0,PC 17477,69.3,B35,C,9,?,"Paris, France"
13,1,1,"Barber, Miss. Ellen 'Nellie'",female,26,0,0,19877,78.85,?,S,6,?,?
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80,0,0,27042,30,A23,S,B,?,"Hessle, Yorks"

In [569]:
titanic.value_counts(["sex"])

sex
male      843
female    466
Name: count, dtype: int64

In [577]:
print(type(titanic["age"]))

<class 'pandas.Series'>

In [584]:
titanic["age"] = titanic["age"].resample
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,<bound method NDFrame.resample of 0 <bou...,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,<bound method NDFrame.resample of 0 <bou...,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,<bound method NDFrame.resample of 0 <bou...,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,<bound method NDFrame.resample of 0 <bou...,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,<bound method NDFrame.resample of 0 <bou...,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,<bound method NDFrame.resample of 0 <bou...,1,0,2665,14.4542,?,C,?,328,?
1305,3,0,"Zabour, Miss. Thamine",female,<bound method NDFrame.resample of 0 <bou...,1,0,2665,14.4542,?,C,?,?,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,<bound method NDFrame.resample of 0 <bou...,0,0,2656,7.225,?,C,?,304,?
1307,3,0,"Zakarian, Mr. Ortin",male,<bound method NDFrame.resample of 0 <bou...,0,0,2670,7.225,?,C,?,?,?
1308,3,0,"Zimmerman, Mr. Leo",male,<bound method NDFrame.resample of 0 <bou...,0,0,315082,7.875,?,S,?,?,?