# pandas practice of data cleaning

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv("coin_Bitcoin.csv")

In [6]:
data

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...,...
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [7]:
data.tail(10)

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
2981,2982,Bitcoin,BTC,2021-06-27 23:59:59,34656.127356,32071.757148,32287.523211,34649.644588,3.551164e+10,6.494617e+11
2982,2983,Bitcoin,BTC,2021-06-28 23:59:59,35219.891791,33902.075892,34679.122222,34434.335314,3.389252e+10,6.454428e+11
2983,2984,Bitcoin,BTC,2021-06-29 23:59:59,36542.111018,34252.484892,34475.559697,35867.777735,3.790146e+10,6.723334e+11
2984,2985,Bitcoin,BTC,2021-06-30 23:59:59,36074.759757,34086.151878,35908.388054,35040.837249,3.405904e+10,6.568525e+11
2985,2986,Bitcoin,BTC,2021-07-01 23:59:59,35035.982712,32883.781226,35035.982712,33572.117653,3.783896e+10,6.293393e+11
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [8]:
data.describe()

,SNo,High,Low,Open,Close,Volume,Marketcap
count,2991.000000,2991.000000,2991.000000,2991.000000,2991.000000,2.991000e+03,2.991000e+03
mean,1496.000000,6893.326038,6486.009539,6700.146240,6711.290443,1.090633e+10,1.208761e+11
std,863.571653,11642.832456,10869.032130,11288.043736,11298.141921,1.888895e+10,2.109438e+11
min,1.000000,74.561096,65.526001,68.504997,68.431000,0.000000e+00,7.784112e+08
25%,748.500000,436.179001,422.879486,430.445496,430.569489,3.036725e+07,6.305579e+09
50%,1496.000000,2387.610107,2178.500000,2269.889893,2286.409912,9.460360e+08,3.741503e+10
75%,2243.500000,8733.926948,8289.800459,8569.656494,8576.238715,1.592015e+10,1.499957e+11
max,2991.000000,64863.098908,62208.964366,63523.754869,63503.457930,3.509679e+11,1.186364e+12

In [9]:
data.describe

<bound method NDFrame.describe of        SNo     Name Symbol                 Date          High           Low  \
0        1  Bitcoin    BTC  2013-04-29 23:59:59    147.488007    134.000000
1        2  Bitcoin    BTC  2013-04-30 23:59:59    146.929993    134.050003
2        3  Bitcoin    BTC  2013-05-01 23:59:59    139.889999    107.720001
3        4  Bitcoin    BTC  2013-05-02 23:59:59    125.599998     92.281898
4        5  Bitcoin    BTC  2013-05-03 23:59:59    108.127998     79.099998
...    ...      ...    ...                  ...           ...           ...
2986  2987  Bitcoin    BTC  2021-07-02 23:59:59  33939.588699  32770.680780
2987  2988  Bitcoin    BTC  2021-07-03 23:59:59  34909.259899  33402.696536
2988  2989  Bitcoin    BTC  2021-07-04 23:59:59  35937.567147  34396.477458
2989  2990  Bitcoin    BTC  2021-07-05 23:59:59  35284.344430  33213.661034
2990  2991  Bitcoin    BTC  2021-07-06 23:59:59  35038.536363  33599.916169

              Open         Close        Volume     Marketcap
0       134.444000    144.539993  0.000000e+00  1.603769e+09
1       144.000000    139.000000  0.000000e+00  1.542813e+09
2       139.000000    116.989998  0.000000e+00  1.298955e+09
3       116.379997    105.209999  0.000000e+00  1.168517e+09
4       106.250000     97.750000  0.000000e+00  1.085995e+09
...            ...           ...           ...           ...
2986  33549.600177  33897.048590  3.872897e+10  6.354508e+11
2987  33854.421362  34668.548402  2.438396e+10  6.499397e+11
2988  34665.564866  35287.779766  2.492431e+10  6.615748e+11
2989  35284.344430  33746.002456  2.672155e+10  6.326962e+11
2990  33723.509655  34235.193451  2.650126e+10  6.418992e+11

[2991 rows x 10 columns]>

In [10]:
data.shape

(2991, 10)

In [11]:
print("number of rows : ",data.shape[0])
print("number of columns : ",data.shape[1])

number of rows :  2991
number of columns :  10

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2991 entries, 0 to 2990
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SNo        2991 non-null   int64
 1   Name       2991 non-null   str
 2   Symbol     2991 non-null   str
 3   Date       2991 non-null   str
 4   High       2991 non-null   float64
 5   Low        2991 non-null   float64
 6   Open       2991 non-null   float64
 7   Close      2991 non-null   float64
 8   Volume     2991 non-null   float64
 9   Marketcap  2991 non-null   float64
dtypes: float64(6), int64(1), str(3)
memory usage: 233.8 KB

In [13]:
data.isnull()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
2986,False,False,False,False,False,False,False,False,False,False
2987,False,False,False,False,False,False,False,False,False,False
2988,False,False,False,False,False,False,False,False,False,False
2989,False,False,False,False,False,False,False,False,False,False
2990,False,False,False,False,False,False,False,False,False,False

In [14]:
data.isna().sum() # it is use to check null values in every columns

SNo          0
Name         0
Symbol       0
Date         0
High         0
Low          0
Open         0
Close        0
Volume       0
Marketcap    0
dtype: int64

In [15]:
data.isna().sum(axis=1)  #it is use to check null values in row wise

0       0
1       0
2       0
3       0
4       0
       ..
2986    0
2987    0
2988    0
2989    0
2990    0
Length: 2991, dtype: int64

In [16]:
data.describe(include="all")

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
count,2991.000000,2991,2991,2991,2991.000000,2991.000000,2991.000000,2991.000000,2.991000e+03,2.991000e+03
unique,NaN,1,1,2991,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Bitcoin,BTC,2013-04-29 23:59:59,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,2991,2991,1,NaN,NaN,NaN,NaN,NaN,NaN
mean,1496.000000,NaN,NaN,NaN,6893.326038,6486.009539,6700.146240,6711.290443,1.090633e+10,1.208761e+11
std,863.571653,NaN,NaN,NaN,11642.832456,10869.032130,11288.043736,11298.141921,1.888895e+10,2.109438e+11
min,1.000000,NaN,NaN,NaN,74.561096,65.526001,68.504997,68.431000,0.000000e+00,7.784112e+08
25%,748.500000,NaN,NaN,NaN,436.179001,422.879486,430.445496,430.569489,3.036725e+07,6.305579e+09
50%,1496.000000,NaN,NaN,NaN,2387.610107,2178.500000,2269.889893,2286.409912,9.460360e+08,3.741503e+10
75%,2243.500000,NaN,NaN,NaN,8733.926948,8289.800459,8569.656494,8576.238715,1.592015e+10,1.499957e+11
max,2991.000000,NaN,NaN,NaN,64863.098908,62208.964366,63523.754869,63503.457930,3.509679e+11,1.186364e+12

In [17]:
# checking unique value in in spacific columns
data["Symbol"].unique()

<StringArray>
['BTC']
Length: 1, dtype: str

In [18]:
data

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...,...
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [19]:
len(data["High"].unique())

2981

In [20]:
data["Name"].unique()

<StringArray>
['Bitcoin']
Length: 1, dtype: str

In [21]:
data.head()

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.0,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.0,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.0,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.0,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.0,1.085995e+09

In [22]:
data["Date"].unique()

<StringArray>
['2013-04-29 23:59:59', '2013-04-30 23:59:59', '2013-05-01 23:59:59',
 '2013-05-02 23:59:59', '2013-05-03 23:59:59', '2013-05-04 23:59:59',
 '2013-05-05 23:59:59', '2013-05-06 23:59:59', '2013-05-07 23:59:59',
 '2013-05-08 23:59:59',
 ...
 '2021-06-27 23:59:59', '2021-06-28 23:59:59', '2021-06-29 23:59:59',
 '2021-06-30 23:59:59', '2021-07-01 23:59:59', '2021-07-02 23:59:59',
 '2021-07-03 23:59:59', '2021-07-04 23:59:59', '2021-07-05 23:59:59',
 '2021-07-06 23:59:59']
Length: 2991, dtype: str

In [23]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2991 entries, 0 to 2990
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SNo        2991 non-null   int64
 1   Name       2991 non-null   str
 2   Symbol     2991 non-null   str
 3   Date       2991 non-null   str
 4   High       2991 non-null   float64
 5   Low        2991 non-null   float64
 6   Open       2991 non-null   float64
 7   Close      2991 non-null   float64
 8   Volume     2991 non-null   float64
 9   Marketcap  2991 non-null   float64
dtypes: float64(6), int64(1), str(3)
memory usage: 233.8 KB

In [24]:
data["Date"]

0       2013-04-29 23:59:59
1       2013-04-30 23:59:59
2       2013-05-01 23:59:59
3       2013-05-02 23:59:59
4       2013-05-03 23:59:59
               ...
2986    2021-07-02 23:59:59
2987    2021-07-03 23:59:59
2988    2021-07-04 23:59:59
2989    2021-07-05 23:59:59
2990    2021-07-06 23:59:59
Name: Date, Length: 2991, dtype: str

In [25]:
data

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Bitcoin,BTC,2013-04-29 23:59:59,147.488007,134.000000,134.444000,144.539993,0.000000e+00,1.603769e+09
1,2,Bitcoin,BTC,2013-04-30 23:59:59,146.929993,134.050003,144.000000,139.000000,0.000000e+00,1.542813e+09
2,3,Bitcoin,BTC,2013-05-01 23:59:59,139.889999,107.720001,139.000000,116.989998,0.000000e+00,1.298955e+09
3,4,Bitcoin,BTC,2013-05-02 23:59:59,125.599998,92.281898,116.379997,105.209999,0.000000e+00,1.168517e+09
4,5,Bitcoin,BTC,2013-05-03 23:59:59,108.127998,79.099998,106.250000,97.750000,0.000000e+00,1.085995e+09
...,...,...,...,...,...,...,...,...,...,...
2986,2987,Bitcoin,BTC,2021-07-02 23:59:59,33939.588699,32770.680780,33549.600177,33897.048590,3.872897e+10,6.354508e+11
2987,2988,Bitcoin,BTC,2021-07-03 23:59:59,34909.259899,33402.696536,33854.421362,34668.548402,2.438396e+10,6.499397e+11
2988,2989,Bitcoin,BTC,2021-07-04 23:59:59,35937.567147,34396.477458,34665.564866,35287.779766,2.492431e+10,6.615748e+11
2989,2990,Bitcoin,BTC,2021-07-05 23:59:59,35284.344430,33213.661034,35284.344430,33746.002456,2.672155e+10,6.326962e+11
2990,2991,Bitcoin,BTC,2021-07-06 23:59:59,35038.536363,33599.916169,33723.509655,34235.193451,2.650126e+10,6.418992e+11

In [31]:
data.columns

Index(['SNo', 'Name', 'Symbol', 'Date', 'High', 'Low', 'Open', 'Close',
       'Volume', 'Marketcap'],
      dtype='str')